# Name of our automated workflow
name: Deploy Fraud News Agent to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    # This job will run on a fresh, clean version of Ubuntu Linux
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out a copy of your code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # ▼▼▼ NEW DEBUGGING STEP ▼▼▼
      # This will show us what files are in the workspace BEFORE the Docker step
      - name: List files in workspace
        run: ls -laR

      # Step 2: Build the package, now with an internal file listing for debug
      - name: Build deployment package inside Lambda container
        uses: docker://public.ecr.aws/sam/build-python3.13
        with:
          entrypoint: /bin/bash
          # I've added a command at the start to list files from INSIDE the container
          args: > 
            -c "
              echo '--- Listing files inside /var/task from the container ---' &&
              ls -laR /var/task/ &&
              echo '--- Starting build ---' &&
              pip install --upgrade pip
              pip install -r /var/task/requirements.txt -t /asset-output/package &&
              cp /var/task/lambda_function.py /asset-output/package/ &&
              cd /asset-output/package &&
              zip -r ../deployment_package.zip .
            "

      # The rest of the steps remain the same...
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1 

      - name: Deploy to AWS Lambda
        run: aws lambda update-function-code --function-name FraudNewsAgent --zip-file fileb://deployment_package.zip